"""
2025 Monthly Migration Data
"""

def get_month_transactions(month):
    """Get transactions for a specific month (1-11 for Jan-Nov)"""
    
    monthly_data = {
        1: [  # JANUARY - Updated with correct spreadsheet data
            {'date': '2025-01-15', 'amount': 12230.64, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 8724.26, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 613.04, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 3569.36, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 4858.83, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 1146.86, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 816.22, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 1790.90, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-01-15', 'amount': 191.44, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-01-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 441.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 1066.13, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 722.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-01-15', 'amount': 600.00, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 88.33, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-01-15', 'amount': 165.78, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
            {'date': '2025-01-15', 'amount': 3394.94, 'type': 'Investment', 'description': 'Gold Investment', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
        ],
        2: [  # FEBRUARY
            {'date': '2025-02-15', 'amount': 12720.18, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 8396.41, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 560.16, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 3569.36, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 4858.83, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 1146.86, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 801.02, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 1767.28, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-02-15', 'amount': 217.20, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-02-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 441.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 1068.12, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 717.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-02-15', 'amount': 689.83, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 228.13, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-02-15', 'amount': 191.88, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
            {'date': '2025-02-15', 'amount': 1444.41, 'type': 'Investment', 'description': 'Gold Investment', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
        ],
        3: [  # MARCH
            {'date': '2025-03-15', 'amount': 13402.29, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 8171.52, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 580.07, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 3569.36, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 4858.83, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 1146.86, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 257.68, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 945.74, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-03-15', 'amount': 2874.37, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-03-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 433.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 1043.35, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 713.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-03-15', 'amount': 800.00, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 862.53, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-03-15', 'amount': 288.83, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 500.00, 'type': 'Transfer', 'description': 'Saving Bank Transfer', 'category': 'Savings', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 1312.50, 'type': 'Investment', 'description': 'Robinhood Investment', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-03-15', 'amount': 100.00, 'type': 'Expense', 'description': 'Extra Payment to Principal', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
        ],
        4: [  # APRIL
            {'date': '2025-04-15', 'amount': 13304.89, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 7647.89, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 533.66, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 3569.36, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 4368.77, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 1146.86, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 2271.78, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 511.24, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-04-15', 'amount': 1399.02, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-04-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 431.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 1043.35, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 709.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-04-15', 'amount': 1210.97, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 912.85, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-04-15', 'amount': 215.47, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 12000.00, 'type': 'Investment', 'description': 'Robinhood Investment', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-04-15', 'amount': 700.00, 'type': 'Expense', 'description': 'Extra Payment to Principal', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
        ],
        5: [  # MAY
            {'date': '2025-05-15', 'amount': 13674.79, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 7012.87, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 567.61, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 3569.36, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 4368.77, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 1146.86, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 2567.08, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 430.40, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-05-15', 'amount': 1529.47, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-05-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 431.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 1043.35, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 705.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-05-15', 'amount': 1150.17, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 660.81, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-05-15', 'amount': 254.79, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-05-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
        ],
        6: [  # JUNE
            {'date': '2025-06-15', 'amount': 12533.55, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 6559.42, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 524.48, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 3569.36, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 4368.77, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 1146.86, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 3362.88, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 833.20, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-06-15', 'amount': 833.04, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-06-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 429.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 1043.35, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 701.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-06-15', 'amount': 1200.00, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 830.36, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-06-15', 'amount': 284.08, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
            {'date': '2025-06-15', 'amount': 1400.00, 'type': 'Expense', 'description': 'Extra Payment to Principal', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
        ],
        7: [  # JULY
            {'date': '2025-07-15', 'amount': 15424.71, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-07-15', 'amount': 6892.71, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 610.52, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 4848.40, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-07-15', 'amount': 2939.94, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-07-15', 'amount': 852.80, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-07-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-07-15', 'amount': 2372.07, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-07-15', 'amount': 6439.06, 'type': 'Expense', 'description': 'Travel Funds', 'category': 'Travel', 'payment_method': 'Credit Card'},
            {'date': '2025-07-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 429.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 1043.35, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 697.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-07-15', 'amount': 1200.00, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 1001.76, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-07-15', 'amount': 315.11, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
            {'date': '2025-07-15', 'amount': 680.00, 'type': 'Investment', 'description': 'Robinhood Investment', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
        ],
        8: [  # AUGUST
            {'date': '2025-08-15', 'amount': 15316.41, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-08-15', 'amount': 7747.33, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 623.53, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 4848.40, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-08-15', 'amount': 1537.74, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-08-15', 'amount': 2488.68, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-08-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-08-15', 'amount': 1700.00, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-08-15', 'amount': 1786.16, 'type': 'Expense', 'description': 'Travel Funds', 'category': 'Travel', 'payment_method': 'Credit Card'},
            {'date': '2025-08-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 429.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 1043.35, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 693.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-08-15', 'amount': 1700.00, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 1274.94, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-08-15', 'amount': 328.02, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-08-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
        ],
        9: [  # SEPTEMBER
            {'date': '2025-09-15', 'amount': 15314.06, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-09-15', 'amount': 5230.24, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 491.84, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 4848.40, 'type': 'Income', 'description': 'BOX RSU', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-09-15', 'amount': 1432.04, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-09-15', 'amount': 2450.28, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-09-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-09-15', 'amount': 581.29, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-09-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 1605.71, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 429.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 952.36, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 690.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-09-15', 'amount': 2066.00, 'type': 'Expense', 'description': 'Discover Debt Payment', 'category': 'Credit Card', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 865.13, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-09-15', 'amount': 296.70, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-09-15', 'amount': 3.08, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
        ],
        10: [  # OCTOBER
            {'date': '2025-10-15', 'amount': 13106.35, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-10-15', 'amount': 7541.23, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 564.91, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 3565.92, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-10-15', 'amount': 1143.42, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-10-15', 'amount': 1323.27, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-10-15', 'amount': 2631.15, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-10-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-10-15', 'amount': 5207.80, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-10-15', 'amount': 486.97, 'type': 'Expense', 'description': 'Travel Funds', 'category': 'Travel', 'payment_method': 'Credit Card'},
            {'date': '2025-10-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 1955.32, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 429.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 952.36, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 686.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-10-15', 'amount': 1045.91, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-10-15', 'amount': 279.74, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-10-15', 'amount': 38.66, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
        ],
        11: [  # NOVEMBER
            {'date': '2025-11-15', 'amount': 13625.32, 'type': 'Income', 'description': 'Monthly Salary', 'category': 'Salary', 'payment_method': 'Direct Deposit'},
            {'date': '2025-11-15', 'amount': 7706.31, 'type': 'Expense', 'description': 'Taxes Paid', 'category': 'Tax', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 664.78, 'type': 'Income', 'description': 'Interest Income', 'category': 'Investment', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 3565.92, 'type': 'Income', 'description': 'BOX STOCKS ESPP', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-11-15', 'amount': 1143.42, 'type': 'Income', 'description': 'BOX ESPP PROFIT', 'category': 'Investment', 'payment_method': 'Direct Deposit'},
            {'date': '2025-11-15', 'amount': 1161.60, 'type': 'Income', 'description': '401K Pretax', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-11-15', 'amount': 2792.82, 'type': 'Investment', 'description': '401k Roth Contribution', 'category': 'Retirement', 'payment_method': 'Direct Deposit'},
            {'date': '2025-11-15', 'amount': 545.82, 'type': 'Income', 'description': 'HSA', 'category': 'Healthcare', 'payment_method': 'Direct Deposit'},
            {'date': '2025-11-15', 'amount': 4892.44, 'type': 'Expense', 'description': 'Credit Card Spending', 'category': 'Credit Card', 'payment_method': 'Credit Card'},
            {'date': '2025-11-15', 'amount': 968.18, 'type': 'Expense', 'description': 'Travel Funds', 'category': 'Travel', 'payment_method': 'Credit Card'},
            {'date': '2025-11-15', 'amount': 6433.39, 'type': 'Expense', 'description': 'Mortgage Payment', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 1955.32, 'type': 'Expense', 'description': 'Property Tax', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 429.00, 'type': 'Expense', 'description': 'HOA Fee', 'category': 'Housing', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 952.36, 'type': 'Expense', 'description': 'Car Loan + Insurance', 'category': 'Transportation', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 683.00, 'type': 'Expense', 'description': 'Sofa and Tiffany', 'category': 'Shopping', 'payment_method': 'Credit Card'},
            {'date': '2025-11-15', 'amount': 895.10, 'type': 'Expense', 'description': 'Groceries/Food', 'category': 'Food', 'payment_method': 'Credit Card'},
            {'date': '2025-11-15', 'amount': 371.42, 'type': 'Expense', 'description': 'Electric + Phone + Wifi Bills', 'category': 'Utilities', 'payment_method': 'Bank Transfer'},
            {'date': '2025-11-15', 'amount': 38.66, 'type': 'Expense', 'description': 'Home Insurance', 'category': 'Insurance', 'payment_method': 'Bank Transfer'},
        ],
    }
    
    return monthly_data.get(month, [])